### ISSUE TITLE
提案 / Suggestion : 高さ調整。(Plane height adjustment)

### ISSUE THREAD

**Issue by naminode** [nullpon16tera/NullponSpectrum#4]
日本語
こんにちは。日本語の話し方がわかりません。この翻訳が十分に良いことを願っています。

私はあなたが作ったmodが大好きです。しかし、VMCを使用していないので、1つの問題があります。問題は、NalululunaAvatarModの平面補正をオンにしているため、モデルの脚が26または32バンドのビジュアライザーをクリップすることです。

English
Hello . I don't know how to speak Japanese language. Hope this translation is good enough.

I love the mod that you made. But I have one problem since im not using VMC. The problem is that my model's legs will clip through the 26 or 32 band visualizer  when I have plane correction turn on for Nalululuna avatar mod.

It would be great if you have height adjustment for the plane added to the mod.

**Comment by nullpon16tera** [comment]
@naminode 
I don't speak English either, so I rely on Google Translate.

Thank you for your report.
Let's verify the operation of NalulunaAvatarMod.

**Comment by nullpon16tera** [comment]
@naminode 
I'm not using NalulunaAvatars, so I don't know what the settings are.
Can you tell me the settings if you like?

**Comment by naminode** [comment]
Below 2 settings are the one I used to adjust the in game plane.
以下の2つの設定は、ゲーム内で調整するために使用した設定です。

Without NalululunaAvatar adjustment. The model legs will clip through the base plane.
NalululunaAvatarの調整なし。モデルの脚がベース平面をクリップします。
![image](https://user-images.githubusercontent.com/88361811/169826522-ef966aa1-35ef-46ae-893e-5bf9d05781ce.png)

So to correct this , I will need to enable the 'Ground Adjustment' option. What this option do is it lowers the base to where the base of the feet is.
したがって、これを修正するには、「グラウンド調整」オプションを有効にする必要があります。このオプションが行うことは、足の付け根がある場所まで足元を下げることです。
![image](https://user-images.githubusercontent.com/88361811/169826798-3d656309-597b-4c0b-8bf5-861b20039823.png)
![image](https://user-images.githubusercontent.com/88361811/169826896-91403774-b543-45b4-aacf-c5f4dacf2241.png)

When I enable the band 26 or band 32 Visualizer. Base visualizer is still at the original base position as shown as in the picture below.
バンド26または32ビジュアライザーを有効にすると。下の図に示すように、ベースビジュアライザーはまだ元のベース位置にあります。
![image](https://user-images.githubusercontent.com/88361811/169827451-ddcae5ab-a36c-410a-8d8b-4741bf6d3288.png)

**Comment by nullpon16tera** [comment]
@naminode 
Thank you for the setting information!
It will be after tomorrow's work is over, but I received an answer from Mr. Naluluna, so I will try to repair it.

**Comment by nullpon16tera** [comment]
@naminode 
Added support for floor adjustment of NalulunaAvatars.
https://github.com/nullpon16tera/NullponSpectrum/releases/tag/0.0.6

**Comment by naminode** [comment]
Just tested today. Works fine. 
![image](https://user-images.githubusercontent.com/88361811/170836094-940f7618-48b1-4c8b-8b28-82b365b51a86.png)

Thank you for the fast fix.
